name: $(Build.BuildId)

pool: 
  vmImage: 'macOS-12'

steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: 'sdk'
      version: '7.0.400'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: PowerShell@2
    displayName: Cake nuget packages
    inputs:
      targetType: 'inline'
      script: |
        dotnet new tool-manifest
        dotnet workload install ios android
        dotnet tool install Cake.Tool --version 3.1.0
        dotnet cake --target nuget
      pwsh: true
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.SourcesDirectory)/output/*.nupkg;!$(Build.SourcesDirectory)/output/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'FocusBrands_Framework'
      allowPackageConflicts: true
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/output'
      artifact: 'packages'
      publishLocation: 'pipeline'