
pool: 
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.400'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  


  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        dotnet new tool-manifest
        dotnet tool install Cake.Tool --version 3.1.0
        cd ./Facebook.Android
        
        dotnet cake --target nuget
      pwsh: true
